title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Artistic Ventures in the hood.. IM super excited this site is for the crafty,musical,artsy souls in the hood
  Forgetting peoples views and making our vision and thoughts of sounds arts and learning explore with me
  It is a each one teach one platform so you can also contribute by blessings us with your crafts.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
